### PR TITLE
add usebasin.com

### PR DESCRIPTION
**Pull request by rmcfadzean**

### CODE REVIEW

**Comment by rmcfadzean** [comment]
Hi @tupaschoal - Yes it is :smile:

**Comment by Nightfirecat** [comment]
Does that button contain a link? If not, a simple description along the lines of "Scroll to the bottom of the page and click the "Completely obliterate all my data" button" would be useful.

**Comment by rmcfadzean** [comment]
Done :+1:

**Comment by tupaschoal** [comment]
Thanks for your contribution!

**Pull request merged**
