### PR TITLE
Add templates for new or updated entry issues

### PR DESCRIPTION
**Pull request by tupaschoal**
This is how the template looks like for each:

# **New Entry**

> # Backstory
> 
> 
> # Data
> 
> 
> - `name`: 
> - `url`: 
> - `url_CODE`: 
> - `difficulty`: 
> 
> - `notes`: 
> - `email`: 
> - `email_subject`: 
> - `email_body`: 
> - `domains`: 

# Update Entry

> # Backstory
> 
> 
> # Data
> 
> 
> - [ ] `name`: 
> - [ ] `url`: 
> - [ ] `difficulty`: 
> - [ ] `notes`: 
> - [ ] `email`: 
> - [ ] `domains`:

### CODE REVIEW

**Comment by PyroSamurai** [comment]
Should we note that only the tags: name, url, difficulty, & domains; are needed for minimum functionality?

**Comment by tupaschoal** [comment]
> Should we note that only the tags: name, url, difficulty, & domains; are needed for minimum functionality?

It kind of is, but it is commented out, so it doesn't show in the preview
```markdown
- `name`: <!-- The name of the service -->
- `url`: <!-- The url of the account-deletion page. If no such page exists, the url should be a contact or help page explaining the process of account deletion -->
- `url_CODE`: <!-- *(optional)* Use the language `CODE` as suffix of the url field to provide language-specific deletion codes, shown on the respective language page -->
- `difficulty`: <!-- one of the difficulties below -->
<!--
    - `easy`: Sites with a simple process such as a 'delete account' button
    - `medium`: Sites that do allow account deletion but require you to perform additional steps
    - `hard`: Sites that require you to contact customer services or those that don't allow automatic or easy account deletion
    - `impossible`: For sites where it's basically impossible to totally delete your account, even if you contact them
-->
- `notes`: <!-- *(optional)* Notes will be shown when someone hovers on that service, they include additional information you might need to delete your account -->
- `email`: <!-- *(optional)* If you have to send an email to a company to cancel your account, add the email address here -->
- `email_subject`: <!-- *(optional)* Set the subject for the email link. If unset, the default text is "Account Deletion Request" -->
- `email_body`: <!-- *(optional)* Set the body for the email link. If unset, the default text is "Please delete my account, my username is XXXXXX" -->
- `domains`: <!-- This is used by the [Chrome extension](https://github.com/jdm-contrib/justdelete.me-chrome-extension) -->
```
I kind of copy+pasted what is in the `CONTRIBUTING` guidelines, I'm feeling like it might be tl;dr

**Comment by PyroSamurai** [comment]
ah, I see. Will the users be able to see it when it is implemented?

**Comment by tupaschoal** [comment]
Yeah, it appears in raw format, just like when you're typing a comment on an issue or describing a PR

**Comment by PyroSamurai** [comment]
ah, okay. Then everything looks good.

**Pull request merged**
