### PR TITLE
Update mediafire service

### PR DESCRIPTION
**Pull request by Gann4Life**
Seems like you don't have to contact them trough e-mail anymore.

### CODE REVIEW

**Comment by Gann4Life** [comment]
> Is the "Delete My Account" button showing up for you?
Yes it did show for me, that's how i deleted my account today, seems weird, sadly i didn't take a screenshot but where you have only one button i had around two or three.

**Review by tupaschoal — COMMENTED** [review]
> Maybe the note could be updated to say that if the button isn't shown, an email must be sent.

This is a good suggestion, I think. We provide both options, in case people only ever see one of them, like @SvicidalBug did.

**Comment by Gann4Life** [comment]
> > Maybe the note could be updated to say that if the button isn't shown, an email must be sent.
> 
> This is a good suggestion, I think. We provide both options, in case people only ever see one of them, like @SvicidalBug did.

My only doubt with this stays on the difficulty, i think i should provide the difficulty as hard straight forward, right?

**Comment by tupaschoal** [comment]
I think medium is fine, since we know it can work on a simpler manner, but it seems to not be guaranteed

**Comment by tupaschoal** [comment]
Thanks for your contribution!

**Pull request merged**
