### PR TITLE
Remove stale

### PR DESCRIPTION
**Pull request by tupaschoal**
These were pointed out by [Build #931](https://travis-ci.org/jdm-contrib/jdm/builds/592863759).
From the commit messages:
> Website stopped responding.
> Social media account seems to be inactive:
> https://twitter.com/cheddarapp
> Failed to respond to request
> Social media account inactive for > 5y
> https://twitter.com/icebergsapp

MyFritz is also timing out, but it has an active social media account and was added a month ago, so I'm considering it might be a temporary issue.

### CODE REVIEW

**Comment by tupaschoal** [comment]
Ok

**Comment by tupaschoal** [comment]
As of October 7, `Cheddar` is back online, but not `Iceber.gs`

**Comment by Nightfirecat** [comment]
Let's drop the commit for cheddar then.

**Comment by tupaschoal** [comment]
Dropped the `cheddar` commit and merged with removal of `Iceber.gs`

**Pull request merged**
