### PR TITLE
Add Opensearch

### LINKED ISSUE #917: 🤔 Suggestion: Add an OpenSearch description file
By adding OpenSearch description the browser will treat the site as a search engine, so we do not have to open the site to search for a service, but doing it directly from the browser's search bar.
_Rather then saving the website as a bookmark i woud like to have it directly in the browser's search bar._

When the site has an OpenSearch description, you will get a button in the browser to add it as a search engine so you can use it when ever you want by type some thing to the search bar then click on the website's favicon.
Also you can have some search suggestions, although it only works with Firefox.

It shoud be very easy to implement sinse the search functionality uses the url `https://justdeleteme.xyz/#{searchTerms}`

[This is a documentation in MDN.](https://developer.mozilla.org/en-US/docs/Web/OpenSearch)
[This is a documentation in the GitHub repository.](https://github.com/dewitt/opensearch/blob/master/opensearch-1-1-draft-6.md)

# Those are some examples:
### Google Translate
https://translate.google.com/opensearch.xml
### DuckDuckGo
https://duckduckgo.com/opensearch.xml
### StackOverFlow
https://stackoverflow.com/opensearch.xml
### GitHub
https://github.com/opensearch.xml

### PR DESCRIPTION
**Pull request by arche-dev**
- Resolves  #917

~~*I'm assuming that `_includes/something` translates to `https://justdeleteme.xyz/something`*~~

### CODE REVIEW

**Comment by Nightfirecat** [comment]
`_includes/` is not for static assets, [it's used for template files](https://jekyllrb.com/docs/includes/). This file should be added in the repo root. Other files there are not copied to the site [due to the `exclude` directive of _config.yml](https://github.com/jdm-contrib/jdm/blob/master/_config.yml#L1)

**Comment by arche-dev** [comment]
> `_includes/` is not for static assets, [it's used for template files](https://jekyllrb.com/docs/includes/). This file should be added in the repo root. Other files there are not copied to the site [due to the `exclude` directive of _config.yml](https://github.com/jdm-contrib/jdm/blob/master/_config.yml#L1)

ah ok sure

**Review by Nightfirecat — COMMENTED** [review]
LGTM

**Review by tupaschoal — APPROVED** [review]

**Comment by tupaschoal** [comment]
Thanks for looking into that and solving it :)

**Comment by Nightfirecat** [comment]
It doesn't seem to work for me, [apparently because the `xmlns` attribute of `<OpenSearchDescription>` is not optional.](https://github.com/dewitt/opensearch/blob/master/opensearch-1-1-draft-6.md#the-opensearchdescription-element)

Should be an easy fix: (though one which should be tested locally before merging if possible)
```xml
<OpenSearchDescription xmlns="http://a9.com/-/spec/opensearch/1.1/">
  <!-- ... -->
</OpenSearchDescription>
```

**Pull request merged**
