### PR TITLE
Add Hooked Deals

### PR DESCRIPTION
**Pull request by AverageHelper**
Leaving this PR as a draft in case I can get to a support rep.

EDIT 1: Finally got hold of a support rep. They said they would inquire with Hooked's tech team about deleting my account. They also told me that forgetting my login credentials may be the best recourse.

~~I'll leave this in draft for a while, in case I hear back with other news.~~

EDIT 2: Deletion is a no-go.

### CODE REVIEW

**Comment by tupaschoal** [comment]
> They also told me that forgetting my login credentials may be the best recourse.

Oh no hahahah. Let us know when it's ready for review, then :)

**Comment by AverageHelper** [comment]
No news from support I think this is ready to go.

**Review by tupaschoal — APPROVED** [review]
Wow even changing the password is impossible O_o

**Comment by tupaschoal** [comment]
Thanks for following up, as always!

**Pull request merged**
