### PR TITLE
add vultr

### PR DESCRIPTION
**Pull request by WJehee**
Added [Vultr](https://www.vultr.com/).
But I could not find out if the account is deleted, only that it has been 'closed' and that the data will be retained for X amount of time for legal purposes.

### CODE REVIEW

**Review by tupaschoal — COMMENTED** [review]
If the privacy policy states the account is closed, but not deleted, we usually state it as impossible

**Comment by tupaschoal** [comment]
@WJehee ?

**Comment by WJehee** [comment]
Execuse me, I have been away for the past week.
I will look into what actually is done with the closed account / information and update the entry accordingly, I will mention you when I have done so!

**Comment by tupaschoal** [comment]
Alright, thank you!

**Comment by WJehee** [comment]
@tupaschoal
I have updated the entry, it seems that closing the account does not remove the information, but a seperate request to customer support does.
So I have changed the difficulty to Hard and added the instructions

**Comment by tupaschoal** [comment]
Thanks for following up!

**Pull request merged**
