### PR TITLE
Add monkeytype

### PR DESCRIPTION
**Pull request by arche-dev**

### CODE REVIEW

**Review by tupaschoal — COMMENTED** [review]
Is there a place where this email is visible? Otherwise I'd not include it, seems personal

**Comment by arche-dev** [comment]
> Is there a place where this email is visible? Otherwise I'd not include it, seems personal

it's on their github: https://github.com/Miodec

**Comment by arche-dev** [comment]
I searched through the website and found  jack@monkeytype.com, going to add that email then

source: https://monkeytype.com/privacy-policy

**Review by tupaschoal — APPROVED** [review]

**Comment by tupaschoal** [comment]
Thanks!

**Pull request merged**
