### PR TITLE
Removing all Wikipedia domains

### PR DESCRIPTION
**Pull request by alrjunior**
Removing all Wikipedia domains and replacing them for only one domain (wikipedia.org). In order to JSON file gets a bit smaller.

### CODE REVIEW

**Comment by Kefaku** [comment]
The problem is: All other language Wikipedia pages will no longer be recognized by the browser extension, if you remove them from the list.

**Comment by alrjunior** [comment]
Really? I thought language domains were subdomains of wikipedia and they'd be recognized like that.

OK, I'm going to close and delete this PR.

**Comment by Kefaku** [comment]
> Really? I thought language domains were subdomains of wikipedia and they'd be recognized like that.
> 
> OK, I'm going to close and delete this PR.

@alrjunior 

No, subdomains like `wikipedia.org/<something>` are included in `wikipedia.org`, while something like `en.wikipedia.org` is not included.

**Comment by tupaschoal** [comment]
Yeah, I think the extension should do partial matching, but unfortunately that is how it works currently.

**Comment by Kefaku** [comment]
> Yeah, I think the extension should do partial matching, but unfortunately that is how it works currently.

@tupaschoal 

With partial matching we would have problems with something like Zendesk, cuz many services use that and it has been included in their domain list.
For example Website1 uses `<website1>.zendesk.com` and Website2 `<website2>.zendesk.com`. That would no longer work with partial matching.

**Comment by tupaschoal** [comment]
True, but I mean partial matching as a fallback (and checking of there aren't multiple matches).

**Pull request closed without merging**
