### PR TITLE
Added QIWI Wallet

### PR DESCRIPTION
**Pull request by hooddy**

### CODE REVIEW

**Review by tupaschoal — COMMENTED** [review]
The entry looks ok, but the entries are sorted by `name`

**Comment by hooddy** [comment]
i don't get what should i do right now to fix it.

**Comment by SvicidalBug** [comment]
> i don't get what should i do right now to fix it.

All entries are listed in alphabetical order based on their names. In this case, `QIWI Wallet` should come just before `Quantic Foundry`.

**Comment by hooddy** [comment]
> > i don't get what should i do right now to fix it.
> 
> All entries are listed in alphabetical order based on their names. In this case, `QIWI Wallet` should come just before `Quantic Foundry`.

Should i need to reedit/repull it again or its autoproccess? I mead that...

**Comment by SvicidalBug** [comment]
> Should i need to reedit/repull it again or its autoproccess? I mean that...

I'm not sure I understand. Any new commits to [your fork](https://github.com/hooddy/jdm/tree/patch-1) will be automatically added to this pull request.

**Comment by hooddy** [comment]
> All entries are listed in alphabetical order based on their names. In this case, `QIWI Wallet` should come just before `Quantic Foundry`.

I was forced to create a new pull request. I'm sorry if I did something wrong, I didn't understand how to fix the rejected one.
It's strange that there are no auto-sorting. And I don't understand how the letters of the national alphabets like Turkish Ç especial if name is starded with itare sorted. Did it just drop it at the end of Latin ABC?

**Comment by tupaschoal** [comment]
The language script is not the smartest and it sorts by ASCII sorting, that's why some special characters come at the end

**Pull request closed without merging**
