### PR TITLE
Create gr.html

### PR DESCRIPTION
**Pull request by zernex201**
Greek translation is ready to be uploaded.

### CODE REVIEW

**Comment by Nightfirecat** [comment]
This file should be added to #410 instead of being in a standalone PR.

**Comment by zernex201** [comment]
I'm new to github and I really don't know how to fix that.

**Comment by Nightfirecat** [comment]
If you can make the other changes needed in #410, I can look at adding this file to it.

**Comment by zernex201** [comment]
thank you. I fixed the "fancy quotes" but I'm not sure whether I updated the #410 or #409 file

**Pull request closed without merging**
