### PR TITLE
DEV.to now has a delete account button

### PR DESCRIPTION
**Pull request by swalladge**
As in the title. :)

### CODE REVIEW

**Comment by tupaschoal** [comment]
Nice, thanks for the update!

**Comment by swalladge** [comment]
@tupaschoal would you mind adding the `hacktoberfest-accepted` label to this PR so it counts towards [Hacktoberfest](https://hacktoberfest.digitalocean.com/)?  Totally understand if you don't want to due to the possibility of attracting spam. :)

**Comment by tupaschoal** [comment]
I mean, it's already merged, so it shouldn't require the label. We would have to add the topic to the repo, but I don't want to because this repo is very spam-prone, sorry :(

**Comment by swalladge** [comment]
@tupaschoal fair enough. :) Apparently you can add the hacktoberfest-accepted label to individual PRs so only those PRs count, as an alternative to the hacktoberfest topic (if you'd like to try that instead of the blanket topic label) - according to the FAQ:

> You can still contribute to any public GitHub repository and have it count towards your progress provided that your pull request is labeled with hacktoberfest-accepted.

**Pull request merged**
