### PR TITLE
Turkish notes for every service

### PR DESCRIPTION
**Pull request by ysfchn**
Hi, I just translated all notes to Turkish. I actually finished it a long ago but this time new services have added / or edited so I translated them again. I downloaded all strings and uploaded them to Crowdin (as a private project) to save time when translating the duplicated words etc, and downloaded and merged with `sites.json` after finishing.

However, I need to explain few notes about this PR if you are interested:

* I was actually planning to create a JDM fork that will have constants to reduce duplicate words and display buttons (for example displaying "Delete Account" or etc actions in <kbd>Keyboard Style</kbd> or something) in different styles. So, Turkish notes actually had keys something like `Click on {delete_account} button` in my own translation file, but as there was no feature in JDM itself, I copied the original one and replaced keys to their original values like `Click on "Delete Account" button` for this PR. (I know it doesn't affect anything about JDM just wanted to explain anyway)

* This PR doesn't have notes like `You need to send an e-mail to example@example.com`, so it has instead `You need to send an e-mail to the support` (because e-mail addresses already defined in the `email` key so I didn't think it is needed to include them in the notes too)

### CODE REVIEW

**Review by tupaschoal — COMMENTED** [review]
First of all, thanks! This is huge and probably a lot of effort was put into the making of this!

> I was actually planning to create a JDM fork that will have constants to reduce duplicate words and display buttons (for example displaying "Delete Account" or etc actions in <kbd>Keyboard Style</kbd> or something) in different styles. So, Turkish notes actually had keys something like `Click on {delete_account} button` in my own translation file, but as there was no feature in JDM itself, I copied the original one and replaced keys to their original values like `Click on "Delete Account" button` for this PR. (I know it doesn't affect anything about JDM just wanted to explain anyway)

This looked very cool and we actually have a request for it on https://github.com/jdm-contrib/jdm/issues/653, we would gladly accept a PR :)

> * This PR doesn't have notes like `You need to send an e-mail to example@example.com`, so it has instead `You need to send an e-mail to the support` (because e-mail addresses already defined in the `email` key so I didn't think it is needed to include them in the notes too)

I'm ok with that.

There are two "issues" which I would like to have sorted. They aren't issues per se, because it would work just fine, but I'd prefer if they were tended to, so it looks neater:
1. Restore the empty lines between each entry. This is just aesthetics, but I think it looks cleaner. Take care not to add a new line with trailing whitespaces (CI will fail if you do, but better to get it right out of the bat).
2. Have the `notes_tr` grouped with the other `notes` tags. This also doesn't make any difference functionally, but it helps us when updating an entry

**Comment by ysfchn** [comment]
Done! I restored empty lines and moved the `notes_tr` key to the below of `notes` key, I hope everything is correct now 😄

**Review by tupaschoal — COMMENTED** [review]
Everything seems fine now, there is just a merge conflict problem to solve, let me know if you need help!

**Comment by ysfchn** [comment]
Oh, sorry. Fixed the conflict 😅

**Review by tupaschoal — APPROVED** [review]

**Comment by tupaschoal** [comment]
Thanks for the great work!

**Comment by ysfchn** [comment]
You're welcome! 😊

**Pull request merged**
