### PR TITLE
Added PlantSnap

### PR DESCRIPTION
**Pull request by OfficialMuffin**

### CODE REVIEW

**Comment by OfficialMuffin** [comment]
Ok I'll take a look, thanks :)

**Comment by OfficialMuffin** [comment]
Im getting an error in travis build:
```

HTML-Proofer finished successfully.

Sorting error in _data/sites.json

Keys must be in alphanumeric order. plantsnap needs to come after pixum

The command "./script/cibuild" exited with 2.
```

but there is no such entry as "pixum" before PlantSnap. Theres "Pixlr" but no "pixum"

**Comment by tupaschoal** [comment]
That's because Pixum has been pushed to the master branch after you forked.
You have to sync your fork and resolve the merges. Do:
`git fetch upstream`
`git rebase upstream/master`

**Comment by tupaschoal** [comment]
Are You submitting it on a new PR? We can make it work :P

**Pull request closed without merging**
