### PR TITLE
Replace country flags with single language icon

### LINKED ISSUE #940: Inconsistent Flag Designs
Playing around I noticed the flag design wasn't consistent, with shiny en24 and flat sk24 GoSquared designs both present. Looking at the git history this looks like an issue inherited from the original. I've put together three different solutions in separate branches linked below, happy to make a PR for whichever yous prefer 🙂

### [`png-flags`](https://github.com/Foggalong/jdm/tree/png-flags)

The first just updates all PNG graphics to use the latest versions of GoSquared's shiny variants (judging by the translation docs this is the version they're all supposed to use). This means a small increase in size for each file since the shiny variants are slightly heavier, with the exception of China which is a decrease of several kilobytes (no idea where that icon was from).

It did occur to me while doing this though that this repo depends on [gosquared/flags](https://github.com/gosquared/flags), a stagnant project with no updates in 6 years and no original art files to work from. If a country every changed its flag or there was ever a need for one not in its repository then there'd be problems. That lead to the second solution;

### [`svg-flag`](https://github.com/Foggalong/jdm/tree/svg-flags)

This solution changes the design base to [catamphetamine/country-flag-icons](https://gitlab.com/catamphetamine/country-flag-icons), which like GoSquared Flags is also MIT licensed.

Since it uses vectors though, we're not limited to using what's provided; we can make sure designs are specifically tailored for the size at which they're displayed. I've modified Nikolay's 3:2 originals to be 4:3 (closer to the old design), 16-by-12 pixel icons which are as aligned to the pixel grid as possible. This means for almost\* every image the quality is either the same or improved.

2021-08-29-131227_739x474_scrot

As part of incorporating this in CSS, by increasing the language button size from 24px to 32px we can scale up the same 16px image we use in the dropdown without any degradation in quality. That, together with SVG optimization, means the collective filesize has dropped by almost 40% (26KB to 16KB). It also means we don't have to worry about icons blurring on HD/zoomed displays and the size drop (alongside vectors generally being better for modern web) means using SVG has taken the loadtime from ~135-140ms to ~5ms on average per flag.

| Before | After |
| :-: | :-: |
| 2021-08-29-140104_164x50_scrot | 2021-08-29-140053_179x48_scrot |

\* The obvious standout which has suffered is Greece, but generally consider these designs first drafts. If this is the solution folks want I'll review the colours so that it's not as jarring (as is I think it's just using the official flag hexes) and will happily make tweaks if there's something folks want changing.

### [`emoji-flag`](https://github.com/Foggalong/jdm/tree/emoji-flags)

I found it odd when searching for another design base that there seemed to be a big gap in the market for an open-source, high quality, small size, vector-based flag library. It dawned on me today that a possible reason is flag emoji like 🇬🇧 and 🇸🇰 exist: they're a universal standard, take the onus off ux people to create tiny, good looking flags, and move any image loading overhead from the website to the font renderer.

I mocked up a quick third solution just to see whether this would be possible and it actually works pretty well. The three snags:

1. The menu gets a little funky in RTL languages, with Liquid seemingly not sure where to put the emoji. This could possibly be addressed with some CSS tweaks.

2. There's [essentially zero support for the Catalonia emoji](https://emojipedia.org/flag-for-catalonia-esct/) which would mean we'd have to use an alternative (the fallback seems to be 🏴) or else some clever CSS to put an image there (but then insert inconsistency).

3. I thought I'd misread when I first saw it, but Microsoft doesn't support flag emojis. Apparently they don't want to get "involved in the politics of flags" which seems batshit to me, but hey-ho. Instead they just [display the country code as text](https://twitter.com/emojipedia/status/838509019174174720). This wouldn't break the UI per-say, but would mean it looked worse to everyone accessing the site through Chrome or Edge on Windows which is less than ideal.

2021-08-29-203239_199x638_scrot

The upside is that when it _does_ work, it looks pretty damn sweet (and [Twemoji](https://github.com/twitter/twemoji)'s colours are probably what I'd borrow to finish off the vector versions if you choose that option). The Microsoft issue _could_ be worked around by bringing in an emoji font like Twemoji which supports flags, up to you if you think that's something you'd like me to look into.

### Misc

All three of these updates also:

- Update the docs to be markdownlint compliant (just fixing headers and code blocks)
- Tweak the CSS to fix the vertical alignment of the flag on the language button.

I'd also say, sorry if it's overwhelming that I've done all this for such a small issue! It's mostly been an exercise distracting myself over a difficult weekend and getting to know how Jekyll works. I'll absolutely not be offended no matter which you pick, it's just been a fun problem to look into :blush:

### LINKED ISSUE #972: Problematic usage of flags for languages
[Flags represent nations, not languages](http://www.flagsarenotlanguages.com/). Please use the [‘turnstyle’ language icon](http://www.languageicon.org/) if an icon is necessary and use the language name and/or language code to signify the language.

Some obviously controversial flags: [United Kingdom](https://en.wikipedia.org/wiki/Geographical_distribution_of_English_speakers), [Spain](https://en.wikipedia.org/wiki/Hispanophone), [France](https://en.wikipedia.org/wiki/Geographical_distribution_of_French_speakers), [Portugal](https://en.wikipedia.org/wiki/Geographical_distribution_of_Portuguese_speakers) (though this project uses Brazil (which is consistent with what exactly?)). These examples have more speakers outside the origin country than within and is a very Euro-centric, colonial viewpoint of language to use any flag whatsoever.

Not to mention, many countries have more than one language which further propagates stereotypes or belittlement of minority groups inside those countries.

---

Related: #940, #943

### PR DESCRIPTION
**Pull request by Foggalong**
Fixes #940, reworking the flags used in the translation switcher. Tasks:

- [x] Make designs consistent
- [x] Use SVGs rather than PNGs
- [x] Add `.editorconfig` SVGs 
- [x] Review flag colour scheme
- [x] Find a fix for Greece (has indivisible stripe number)
- [x] Update translation documentation to reflect changes
- [x] Fix issues with red icons on red navbar
- [x] Remove flags entirely, problematic usecase
- [ ] Fix vertical navbar alignment 

Edit: now also fixes #972 and makes #941 less urgent - it doesn't matter any-more what the translation files are called since they're not intrinsically linked to other files or properties in the site.

### CODE REVIEW

**Review by tupaschoal — COMMENTED** [review]
We might have to edit the `.editorconfig` preferences to not match the SVG. I don't think it's worth making the SVGs compliant to any linting rule, specially because we haven't been writing them ourselves.

Most of the `README` changes are not related to the flag switching/fixing, so if you can cherry pick it to another PR, it would be great, as we would be able to merge it sooner and also reduce the size of this one :)

**Comment by Foggalong** [comment]
Done another sweep on icon design on icon, mainly updating colouring and fixing alignment but also done some further size reduction using some SVG wizardry; we're now down to 9.9KB compare to 26KB with the PNGs.

Updated the docs to reflect the move from PNG to SVG and the design base switch. A translator can just drop the relevant flag from [catamphetamine/country-flag-icons](https://gitlab.com/catamphetamine/country-flag-icons/-/blob/master/3x2) into the flags directory without doing any of the resizing or optimization's I've done; JDM's CSS will handle the resizing. It won't necessarily be as aligned to grid as optimized as it could be, but there won't be any glaring issues (example below where I've just dropped Angola's flag from that repo in without making any adjustments) and can be optimized later.

Screenshot from 2021-09-23 22-59-55
Screenshot from 2021-09-23 23-09-49

The one issue I've not managed to solve through icon design is having red flags on a red background. It was a problem with the old flags as well (as below) but this seems the time to fix it.

Screenshot from 2021-09-23 23-16-06 Screenshot from 2021-09-23 23-15-50

The solution I'm leaning toward is changing the colour of the navigation bar to be JDM slate rather than JDM red (example below), but I didn't want to just push that because it's a bit more of a drastic design change.

Screenshot from 2021-09-23 23-17-07

Screenshot from 2021-09-23 23-27-57


The way I'd originally thought I'd be able to fix this was choosing a red which was distinct enough from the navbar to differentiate them, but that's not possible in some cases without really drastically changing the flag which makes it look weird especially on the grey background of the dropdown menu.

Screenshot from 2021-09-23 23-22-48

Another solution might be to add a 1px border around the flag so that there's a clear distinction, but doing that would mean tweaking how the dropdown button works (at the minute the flag is included through a `background-image` CSS property rather than a HTML `<svg>` so can't be modified in-place) so didn't want to start playing with that unless you weren't happy with the navbar change.

You could keep the red navbar and the red flags as is too, I suppose it's an issue already so it wouldn't necessarily be a degradation but figured if there was appetite to fix it this would be the time :slightly_smiling_face:

**Review by tupaschoal — COMMENTED** [review]
> Done another sweep on icon design on icon, mainly updating colouring and fixing alignment but also done some further size reduction using some SVG wizardry; we're now down to 9.9KB compare to 26KB with the PNGs.

That's a great reduction, nice!

> Updated the docs to reflect the move from PNG to SVG and the design base switch. A translator can just drop the relevant flag from catamphetamine/country-flag-icons into the flags directory without doing any of the resizing or optimization's I've done; JDM's CSS will handle the resizing

Great, making this easy to add is definitely a good step forward.

> It won't necessarily be as aligned to grid as optimized as it could be, but there won't be any glaring issues (example below where I've just dropped Angola's flag from that repo in without making any adjustments) and can be optimized later.

How are you optimizing it, anyway? Is it using some tool like https://compressor.io/ or manually? Because depending on how difficult it is, we might describe it somewhere and have people do, or at least the maintainers themselves.

> The one issue I've not managed to solve through icon design is having red flags on a red background. It was a problem with the old flags as well (as below) but this seems the time to fix it.

I think this is currently an issue with just the one flag you mentioned, which is one that does not sport a border, like you suggested below. In any case, a grey flag seems more unlikely than a red one, so I think changing the background color of the header is fine. Fixing it later, though, would be just a matter of changing the background color of the header, so I'm think I'd rather stick with just improving the flags here and fiddling with the header color later, so that we don't stack too many stuff into one PR

**Comment by Foggalong** [comment]
> How are you optimizing it, anyway? Is it using some tool like https://compressor.io/ or manually? Because depending on how difficult it is, we might describe it somewhere and have people do, or at least the maintainers themselves.

The basic optimization is done through Inkscape's [scour](https://github.com/scour-project/scour) integration which anyone can use without difficulty. Beyond that I'm doing some tweaks in a text editor manually based on what I know is and isn't optional in the SVG spec.

>  I think this is currently an issue with just the one flag you mentioned, which is one that does not sport a border, like you suggested below. In any case, a grey flag seems more unlikely than a red one, so I think changing the background color of the header is fine.

The confusion is probably me overcomplicating it with to many mentions of different colours and solutions. The grey mentioned was the white-grey that is the background of the dropdown, not in the icons. The change to the icons as oppose to the header bar was darkening the red that's used; it would mainly benefit China, Morocco, Taiwan Turkey, and Vietname but to a lesser extent all the icons which have red elements on the outside. 

Screenshot from 2021-09-28 16-04-58

The border was a separate suggestion, not something that's actually present on any of the icons (but happy to add it if you want one).

> I'd rather stick with just improving the flags here and fiddling with the header color later, so that we don't stack too many stuff into one PR

That's all good! Assuming you don't want the border or red colour change mentioned above, this is ready to merge :+1:

**Comment by tupaschoal** [comment]
Hey @Foggalong, think you can amend with the notes on `CONTRIBUTING` so we can merge it? :)

**Comment by tupaschoal** [comment]
Thanks for bringing that to our attention @toastal. Though it sounds quite unlikely, I had never actually connected these two points and noticed that it doesn't make sense to have flags to represent languages.

@Foggalong sorry for all the work you've done that won't be used, though you (and I) have learned a lot in the process. Would you want to repurpose this PR to match what is described in #972 instead? Namely dropping all flags and just using the turnstyle icon

**Comment by Foggalong** [comment]
Yeah happy to do that! For what it's worth, I also agree with @toastal - it just never occurred to me that outright removing them was an option. No worries about the spent effort either, I've learned things along the way I'll probably be able to reapply elsewhere.

I've got a free day for FOSS work tomorrow so will get this PR repurposed for that then 🙂

**Comment by tupaschoal** [comment]
Great, thanks!

**Comment by Foggalong** [comment]
This is in theory done but there's a slight vertical alignment issue which persisted through everything I tried today. Happy to either give that another bash this week or else merge for now and come back to that another time.

Screenshot from 2021-10-31 23-49-44

**Review by tupaschoal — APPROVED** [review]
Thanks for all the effort in this task, I've tested the changes here and it looks great. Also I really appreciate the length that you've gone through to find clearly licensed language icons.

I think the alignment issue is a minor one and I'll just open a separate issue to track it.

**Comment by Spectroxx** [comment]
IT seems the country drop-down area is broken now. [IMAGE](https://cdn.discordapp.com/attachments/808095672393924618/907718184231133184/9YpYe2hMrC.gif)

**Comment by Foggalong** [comment]
That's weird, I wasn't seeing that on my local build 😕

**Comment by Spectroxx** [comment]
Does it appear when visiting the JDM website?

**Comment by Foggalong** [comment]
I can't seem to reproduce this error on either my phone or laptop. Anyone else?

**Comment by tupaschoal** [comment]
Yep, seems to be buggy on Windows 10 + Chrome 95.0.4638.69 
jdm

**Comment by Nightfirecat** [comment]
I can reproduce the same on Firefox 94.0.1 installed via Snap. I'm not certain this wasn't a bug prior to this change though, this seems unrelated.

**Comment by tupaschoal** [comment]
I tested it and it was a bug that was already happening.

**Pull request merged**
