### PR TITLE
Add warning that you can't reuse a Steam account name

### PR DESCRIPTION
**Pull request by Leonardo-DGS**

### CODE REVIEW

**Comment by DevBaddy** [comment]
You should probably indicate the other changes you have made in your PR title.

**Comment by Leonardo-DGS** [comment]
That's the only change.

**Comment by DevBaddy** [comment]
Well, I see this commit you added to this PR: [Commit](https://github.com/jdm-contrib/jdm/pull/1644/commits/227729c28871e2066196d7b5e71e9f738558b33e), which looks like you added some websites.

**Comment by Leonardo-DGS** [comment]
They are already merged commits

**Comment by DevBaddy** [comment]
My bad.

**Review by tupaschoal — APPROVED** [review]

**Pull request merged**
