### PR TITLE
Complete spanish translation

### PR DESCRIPTION
**Pull request by sbritorodr**
Translated some english texts into spanish.

### CODE REVIEW

**Comment by sbritorodr** [comment]
The thing is some text are written in informal spanish (Using the 2º person instead of the 3º person) and some lines in formal spanish. We should decide which one we keep to preserve adequation

**Comment by sbritorodr** [comment]
#493

**Comment by tupaschoal** [comment]
> The thing is some text are written in informal spanish (Using the 2º person instead of the 3º person) and some lines in formal spanish. We should decide which one we keep to preserve adequation

Can you name a few occurrences of formal vs informal?

**Comment by sbritorodr** [comment]
> > The thing is some text are written in informal spanish (Using the 2º person instead of the 3º person) and some lines in formal spanish. We should decide which one we keep to preserve adequation
> 
> Can you name a few occurrences of formal vs informal?
Of course.
Formal lines:
11: `   "extensionp2": "nos ha ayudado a lanzar esta increíble extensión de Google Chrome para JustDeleteMe.", `
13: `    "extensionp4": "Para instalarla, entre en la",`

Informal Lines:
12: `  "extensionp3": "Si entras a una web identificada por JustDeleteMe, la extensión te mostrará un punto a la omnibar. Haciendo clic a ese punto, te llevará directamente a la página para borrar tu cuenta.", `

**Comment by tupaschoal** [comment]
I'd say go for formal if you want to make it consistent.

I'll merge this one anyway as it completes the translation, and you can work on reviewing it in another PR :)

Thanks!

**Pull request merged**
