### PR TITLE
Add FastTech

### PR DESCRIPTION
**Pull request by NicolasBizzozzero**

### CODE REVIEW

**Comment by tupaschoal** [comment]
Please resolve the conflicts with the master branch :)

**Comment by NicolasBizzozzero** [comment]
Sorry for my ignorance but I can't understand why it is in conflicts, I forked from the most recent master branch and just added my changes. I thus do not know how to resolve this conflict ...

**Comment by Nightfirecat** [comment]
Hm, that's rather strange. Your repo also says it's only ahead of ours, so I'm not sure either. Could you perhaps create a branch from your master branch and open a PR from that branch? That's about all I can imagine might be the cause.

**Comment by NicolasBizzozzero** [comment]
I created a new PR (https://github.com/jdm-contrib/jdm/pull/387) following @Nightfirecat suggestion, it seems to works now, so I can close this one !

**Pull request closed without merging**
