### PR TITLE
Add Fast2Pay

### PR DESCRIPTION
**Pull request by tupaschoal**

### CODE REVIEW

**Comment by Nightfirecat** [comment]
Have you tried requesting deletion via their [contact link](https://www.fast2pay.com.br/contato)?

**Comment by tupaschoal** [comment]
I did, but haven't heard back. Will update if I do

**Comment by tupaschoal** [comment]
I'll give it a couple days

**Comment by tupaschoal** [comment]
I didn't hear back, so I'm pushing it.

**Pull request merged**
