### PR TITLE
Fix Strava url

### PR DESCRIPTION
**Pull request by crazko**

### CODE REVIEW

**Comment by Nightfirecat** [comment]
Is the rest of the entry aside from the URL still accurate?

**Comment by crazko** [comment]
Well, I didn't check that before, but from the 1. step of that link:

> Account deletion is irreversible: Your account and data will be permanently deleted, and you will be removed from all clubs, heatmaps, challenges and leaderboards. Some data you created for the community, like public segments or routes, may remain on Strava.

I think it's more accurate than notes currently present. Should I change it as well? I don't know about other languages though.

**Comment by tupaschoal** [comment]
Yes, please update it and remove the other languages. Luckily someone will translate them back one day :)

**Comment by crazko** [comment]
updated

**Comment by Nightfirecat** [comment]
Thanks for your contribution!

**Pull request merged**
