### PR TITLE
Turkish Translation (tr.json)

### PR DESCRIPTION
**Pull request by ysfchn**
This PR includes a Turkish translation with:

* [x] The better-translated version of `tr.json`.
* [ ] ~~Turkish notes in `sites.json` for every web service which contains `notes` already for English.~~ - Will make a new PR for it

### CODE REVIEW

**Review by tupaschoal — APPROVED** [review]
This looks great, thanks for doing it!

I'd recommend us merging this PR, so the website translation is up to date, then you can do another one to translate the notes, which is a longer process. What do you think?

**Comment by ysfchn** [comment]
Also, will it cause a problem if I translate website button texts too for the notes? 

For example; 9GAG doesn't have a Turkish language option on their website, so "Delete My Account" text will stay in English on the website but I would like to translate the button texts too because then it would be confusing to have English text on Turkish note.

**Comment by tupaschoal** [comment]
> Also, will it cause a problem if I translate website button texts too for the notes? 
> 
> For example; 9GAG doesn't have a Turkish language option on their website, so the "Delete My Account" text will stay in English on the website but I would like to translate the button texts too otherwise it would be confusing to have English text on Turkish note.


Hmm, I think I prefer having some English on notes than having it translated, because the notes should be as clear as possible in explaining the steps. If the button is in English regardless of the website language, then keep the button text untranslated. Wha do you think?

**Comment by tupaschoal** [comment]
This completes tr for #493

**Comment by ysfchn** [comment]
>  I think I prefer having some English on notes than having it translated, because the notes should be as clear as possible in explaining the steps. 

I prefer having a key something named `constants` in the translations files, so we can translate button/menu texts separately and we can reference it in the notes like `Go to your account, then click {delete_account} button.` so `{delete_account}` will be replaced with the button/menu text as defined in the `constants` object. And it will be easier to modify existing notes because a lot of notes already uses the "Delete Account" text already.

> If the button is in English regardless of the website language, then keep the button text untranslated. 

Also having constants can fix that issue too. We can add the web service's own languages too in `sites.json`. For example; The X web service has Turkish and English languages so if the Turkish language is selected on JustDeleteMe, show the button texts as Turkish too because the web service has Turkish support, otherwise show the English translation of the button texts.

Lastly, it will allow you to show the button texts in a different style on the website. For example:
"Go to your account, then click <kbd>Delete My Account</kbd> button."

What do you think?

**Comment by tupaschoal** [comment]
Hmm, it sounds very cool actually, though I wonder if it's worth the effort of implementing. JDM is all about providing simple instructions on how to delete your account from a service, I'm afraid adding these elements might show up as a bit intimidating to people that aren't savvy programmers.

**Comment by ysfchn** [comment]
I think you're right, I don't want JDM to have complicated code too. Making it complicated will cause fewer contributions. So looks like it will be better to stay with the current for now. 😅

**Pull request merged**
