### PR TITLE
make glovo hard

### PR DESCRIPTION
**Pull request by bali-ibrahim**
Glovo seems to require filling up a free text to be reviewed.

### CODE REVIEW

**Comment by tupaschoal** [comment]
But are the instructions still the same?

**Comment by bali-ibrahim** [comment]
> But are the instructions still the same?

Well, there's one additional step of I guess asking to be deleted? The instructions are about 2 steps longer but seem pretty straightforward except for the last part.

**Comment by tupaschoal** [comment]
Can you please also modify the notes to make them clearer, then?

**Review by tupaschoal — APPROVED** [review]
I reconsidered and I think the notes don't need any addition

**Pull request merged**
