### PR TITLE
Change Skype to impossible

### PR DESCRIPTION
**Pull request by Wolftallemo**

### CODE REVIEW

**Comment by Wolftallemo** [comment]
From what I could find, it appears users were forced to migrate to microsoft accounts.

[1] https://answers.microsoft.com/en-us/skype/forum/all/merge-my-old-skype-account-to-my-new-microsoft/57ace254-731d-4386-9d21-5c24f263a770
[2] https://support.skype.com/en/faq/fa12060/can-i-merge-or-unlink-my-skype-and-microsoft-accounts

**Comment by Wolftallemo** [comment]
At some point they started converting them to microsoft accounts automatically. Although there is still a skype name attached which is why one can still log in with that.

**Comment by Wolftallemo** [comment]
After some more digging, it appears that they were all migrated automatically around late 2016 - early 2017, but some very old accounts need to be updated with an email address to be fully activated (I assume these are also closed using the normal ms account closure link).

- https://answers.microsoft.com/en-us/skype/forum/all/associate-an-old-skype-account-with-new-microsoft/fb17500b-8f6e-4e75-83f1-4042694f1632

**Comment by tupaschoal** [comment]
Nice digging around, it seems impossible is the way to go then, all agree?

**Review by tupaschoal — APPROVED** [review]
Thanks for the investigation folks :)

**Pull request merged**
