### PR TITLE
Added a help link to Curve

### PR DESCRIPTION
**Pull request by OfficialMuffin**

### CODE REVIEW

**Comment by tupaschoal** [comment]
Can you please sync your fork with upstream, so that the diff looks cleaner?

**Comment by PyroSamurai** [comment]
Easy way: delete your fork and fork again, then add your new changes, then make new PR.

**Comment by OfficialMuffin** [comment]
Does this look right?

**Comment by PyroSamurai** [comment]
Made the change for you, the way it should have been done. https://github.com/jdm-contrib/jdm/commit/6d723acd36de5335ba5140f0e745cb7e0f85d2aa

**Comment by tupaschoal** [comment]
Just a note for the future, create a branch every time you need to change something and open the PR from that branch onto our master.

Make sure you sync your [master's](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork) every once in a while (I'd recommend rebase instead of the merge on the tutorial)

**Comment by OfficialMuffin** [comment]
Yeah sorry, I'm still learning how to do branches.
Thanks

**Comment by tupaschoal** [comment]
Don't worry, we've all been there.

**Pull request closed without merging**
