### PR TITLE
Update install command for bundler to be more accurate

### PR DESCRIPTION
**Pull request by stevenmchoi**
This is my very first time forking from an open source project, so I wanted to start off small.

Simply changed `bundler install` to the correct command `bundle install`.

### CODE REVIEW

**Comment by tupaschoal** [comment]
Thanks for the contribution!

**Comment by stevenmchoi** [comment]
Thanks @tupaschoal ! Happy to help! Sorry, had another question: where can I make suggestions for JDM? Do I make it an "issue"? I feel like my idea is more suited for a forum than an issue for the project. I don't see anything like that in the Community profile.

**Comment by tupaschoal** [comment]
We tend to discuss new ideas in issues, no problem. Your concern is about discussing it in public or because it will elevate our "issue" count?

**Comment by stevenmchoi** [comment]
Yeah, just wanted to get a feel for how the jdm community sees "issues"; nothing serious. Thanks! I'll make my suggestion there!

**Pull request merged**
