### PR TITLE
Update Xing url and messages

### PR DESCRIPTION
**Pull request by iamandrewluca**

### CODE REVIEW

**Comment by iamandrewluca** [comment]
😬 I Google Translated "Delete Profile" that is English version

**Comment by tupaschoal** [comment]
I understand, and appreciate the effort, but we recommend people leaving only the languages they speak and erasing the others, when updating a note. Can you do that instead, please?

**Comment by iamandrewluca** [comment]
@tupaschoal Done!

**Review by tupaschoal — APPROVED** [review]

**Comment by iamandrewluca** [comment]
🙌 Happy I could be of help 🚀

**Pull request merged**
