### PR TITLE
Add walmart.ca as hard and update walmart.com

### PR DESCRIPTION
**Pull request by Wolftallemo**
- Changed existing walmart entry to walmart canada
- Remade walmart.com entry with updated information

### CODE REVIEW

**Review by tupaschoal — COMMENTED** [review]
Sorry for the delay in reviewing, but I'm wondering whether it should be split of as a new entry or a note on the same. Though you're not a california resident, have you tried using that method to see if it would work?

**Comment by Wolftallemo** [comment]
The two sites have separate account systems, and I'm still waiting to hear back from walmart although they have you affirm that you are in fact a resident (but don't check the address entered)

**Comment by tupaschoal** [comment]
Ok, let's wait for another week for a response, otherwise we can move it to impossible, if they don't honor their promise.

**Comment by tupaschoal** [comment]
I see you updated with trailing whitespaces fix. Did you also happen to hear back from them?

**Review by tupaschoal — APPROVED** [review]
I'll merge this as is then. If you notice that they do not delete the account, let us know so we can change the difficulty. Thanks for the contribution!

**Pull request merged**
