### PR TITLE
Add Canva and Curve

### PR DESCRIPTION
**Pull request by OfficialMuffin**

### CODE REVIEW

**Comment by PyroSamurai** [comment]
Thanks for your contribution! :)

**Comment by OfficialMuffin** [comment]
Thanks :) the whitespacing and tabs always get me everytime.

**Comment by OfficialMuffin** [comment]
I believe there is an error with Canva as it does not show correctly on the site.

**Comment by tupaschoal** [comment]
Is `curve` just a matter of clicking a button? If so, it should probably be easy, as deleting is easy, just takes long to be effective.

As for `Canva` I think it should be impossible, as you can never fully delete it

**Comment by tupaschoal** [comment]
> I believe there is an error with Canva as it does not show correctly on the site.

I think it might be the uppercase M on medium, not 100% sure though. If it is we need to either lint to prevent it or fix in the architecture

**Comment by PyroSamurai** [comment]
Revert if needed.

**Comment by PyroSamurai** [comment]
Just added a commit to address these possible issues. https://github.com/jdm-contrib/jdm/commit/849b9b046815847f3b7cfacd60d9bc6c9f15494c

**Comment by PyroSamurai** [comment]
Okay, made a new commit addressing the concerns. Hopefully fixes the issues. https://github.com/jdm-contrib/jdm/commit/6bf3acd3883519eee242c26896772c51a53cc7b1

**Comment by OfficialMuffin** [comment]
Yes its fixed. Thanks

**Pull request merged**
