### PR TITLE
aboutyou.it added

### PR DESCRIPTION
**Pull request by MattiaRaffaele**
I added aboutyou.it

### CODE REVIEW

**Comment by tupaschoal** [comment]
@MattiaRaffaele let us help with whatever issue with whichever issue you're having instead of closing and opening new pull requests for every attempt

**Comment by MattiaRaffaele** [comment]
> @MattiaRaffaele let us help with whatever issue with whichever issue you're having instead of closing and opening new pull requests for every attempt

Ok, whenever I try to pull a request I want to pull 1 commit not 4 or more, how can I fix this?

**Comment by MattiaRaffaele** [comment]
> > @MattiaRaffaele let us help with whatever issue with whichever issue you're having instead of closing and opening new pull requests for every attempt
> 
> Ok, whenever I try to pull a request I want to pull the changes that I made not all the changes that I made
>For example I added aboutyou.it and when I try to pull it adds the aboutyou.it commit and the dafont.com commit (I sent dafont.com yesterday and was added to the site)

**Comment by tupaschoal** [comment]
> > @MattiaRaffaele let us help with whatever issue with whichever issue you're having instead of closing and opening new pull requests for every attempt
> 
> Ok, whenever I try to pull a request I want to pull 1 commit not 4 or more, how can I fix this?

When you open a pull request, it will pull all commits on your source branch that do not exist on the target branch (our repo). If you want to pull just one, make sure you create a branch from a clean `master` branch and then do the single commit. What happened is that you are doing commits in your master and since we rename and squash commits on merge, git fails to recognise that those were already added.

If you're not familiar with git, typically the easiest solution to "clean" the master branch is to delete your fork and fork again, and from there only create new commits on new branches

**Comment by MattiaRaffaele** [comment]
> > > @MattiaRaffaele let us help with whatever issue with whichever issue you're having instead of closing and opening new pull requests for every attempt
> > 
> > 
> > Ok, whenever I try to pull a request I want to pull 1 commit not 4 or more, how can I fix this?
> 
> When you open a pull request, it will pull all commits on your source branch that do not exist on the target branch (our repo). If you want to pull just one, make sure you create a branch from a clean `master` branch and then do the single commit. What happened is that you are doing commits in your master and since we rename and squash commits on merge, git fails to recognise that those were already added.
> 
> If you're not familiar with git, typically the easiest solution to "clean" the master branch is to delete your fork and fork again, and from there only create new commits on new branches

Ok thank you very much!

**Pull request closed without merging**
